#modify@zte.com.cn 20160106 modify begin
#include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/drivers/misc/mediatek/magnetometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y	:=  qmcX983.o
#modify@zte.com.cn 20160106 modify end