##modify@zte.com.cn add at 20150805 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += nt35521s_hd720_dsi_vdo_txd_E169F.o

##modify@zte.com.cn add at 20150805 end


