#modify@zte.com.cn  20160921 add comment start
ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/step_counter
ccflags-y += -I$(srctree)/drivers/misc/mediatek/tilt_detector_sensor

obj-y	:=  lis2ds12.o
#modify@zte.com.cn  20160921 add comment end
