##modify@zte.com.cn add at 20160315 begin
ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y	:=  lis2dh12.o
##modify@zte.com.cn add at 20160315 end
