#modify@zte.com.cn 20160323 start
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT915/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT915/include/config_e169f/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT915/include/firmware_e169f/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y	+=  gt9xx_driver.o
obj-y	+=  goodix_tool.o
obj-y	+=  gt9xx_update.o
#modify@zte.com.cn 20160323 end
