#modify@zte.com.cn 20160818 begin
# Makefile for misc devices that really don't fit anywhere else.

custom_cam_cal := $(addsuffix /, $(shell echo $(CONFIG_CUSTOM_KERNEL_CAM_CAL_DRV)))
obj-y += $(custom_cam_cal)
#modify@zte.com.cn 20160818 end